name: docker release

on:
  workflow_dispatch:

jobs:
# ===============================================================
#   Building Dev Images
# ===============================================================
  release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - 
      name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:          
          platforms: arm64,amd64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build dragonfly alpine
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     platforms: linux/amd64,linux/arm64
    #     push: ${{ github.event_name != 'pull_request' }}
    #     tags: |
    #       ghcr.io/${{ github.repository }}/dragonfly:alpine
    #     file: tools/docker/Dockerfile.alpine-prod
    
    - name: Build dragonfly ubuntu
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        build-args: |
          QEMU_CPU='help'
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ghcr.io/${{ github.repository }}/dragonfly:ubuntu
          ghcr.io/${{ github.repository }}/dragonfly:latest
          dragonfly
        file: tools/docker/Dockerfile.ubuntu-prod