name: Version Release

  #on:
  #  push:
  #    tags:
  #    - 'v*'
  #
on:
  # push:
  # branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: temp
          allowUpdates: true
          omitBody: true
          prerelease: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-qemu:
    strategy:
      matrix:
        # Test of these containers
        container: ["ubuntu-dev:20"]
        runner: [[self-hosted, linux, ARM64]]
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/romange/${{ matrix.container }}
    name: Build aarch64 on ubuntu20.04
    needs: create-release
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build artifacts
      run: |
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git describe --always --tags ${{ github.sha }}
          ./tools/release.sh
          ls -lah build-opt
          apt update && apt install -y debhelper moreutils pip jq
          #            ./tools/packaging/generate_debian_package.sh build-opt/dragonfly-aarch64
          #            mv dragonfly_*.deb build-opt/
    - name: Run regression tests
      uses: ./.github/actions/regression-tests
      with:
        dfly-executable: dragonfly-aarch64
        gspace-secret: ${{ secrets.GSPACES_BOT_DF_BUILD }}
        run-only-on-ubuntu-latest: false
        build-folder-name: build-opt
          #    - name: Save artifacts
          #      run: |
          #          # place all artifacts at the same location
          #          mkdir -p results-artifacts
          #          mv build-opt/dragonfly-*tar.gz results-artifacts
          #          mv dragonfly_*.deb results-artifacts
          #    - name: Upload
          #      uses: actions/upload-artifact@v3
          #      with:
          #        name: dragonfly-aarch64
          #        path: results-artifacts/*
          #
  build-native:
    runs-on: ubuntu-latest
    needs: create-release
    container:
      image: ghcr.io/romange/ubuntu-dev:20
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Configure
      run: |
          apt update && apt install -y debhelper moreutils pip jq
    - name: Build artifacts
      run: |
          # Work around https://github.com/actions/checkout/issues/766
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git describe --always --tags ${{ github.sha }}
          ./tools/release.sh
          # once the build is over, we want to generate a Debian package
          #./tools/packaging/generate_debian_package.sh build-opt/dragonfly-x86_64
    - name: Run regression tests
      uses: ./.github/actions/regression-tests
      with:
        dfly-executable: dragonfly-x86_64
        gspace-secret: ${{ secrets.GSPACES_BOT_DF_BUILD }}
        run-only-on-ubuntu-latest: false
        build-folder-name: build-opt
    - name: Gen(should fail)
      run: |
          ./tools/packaging/generate_debian_package.sh build-opt/dragonfly-x86_64
          #    - name: Save artifacts
          #      run: |
          #          # place all artifacts at the same location
          #          mkdir -p results-artifacts
          #          mv build-opt/dragonfly-*tar.gz results-artifacts
          #          mv dragonfly_*.deb results-artifacts
          #    - name: Upload
          #      uses: actions/upload-artifact@v3
          #      with:
          #        name: dragonfly-amd64
          #        path: results-artifacts/*
          #  publish_release:
          #    runs-on: ubuntu-latest
          #    needs: [build-native, build-qemu]
          #    steps:
          #      - uses: actions/download-artifact@v3
          #        name: Download files
          #        with:
          #          path: artifacts
          #      - name: See all the artifacts
          #        run: |
          #          ls -lR artifacts/
          #      - uses: ncipollo/release-action@v1
          #        with:
          #          artifacts: "artifacts/dragonfly-*/*"
          #          allowUpdates: true
          #          draft: true
          #          prerelease: true
          #          omitNameDuringUpdate: true
          #          token: ${{ secrets.GITHUB_TOKEN }}
